[{
  ...groupBaseOption,
  'AD - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ad.svg',
}, {
  ...groupBaseOption,
  'AE - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ae.svg',
}, {
  ...groupBaseOption,
  'AF - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/af.svg',
}, {
  ...groupBaseOption,
  'AG - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ag.svg',
}, {
  ...groupBaseOption,
  'AI - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ai.svg',
}, {
  ...groupBaseOption,
  'AL - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/al.svg',
}, {
  ...groupBaseOption,
  'AM - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/am.svg',
}, {
  ...groupBaseOption,
  'AO - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ao.svg',
}, {
  ...groupBaseOption,
  'AQ - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/aq.svg',
}, {
  ...groupBaseOption,
  'AR - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ar.svg',
}, {
  ...groupBaseOption,
  'AS - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/as.svg',
}, {
  ...groupBaseOption,
  'AT - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/at.svg',
}, {
  ...groupBaseOption,
  'AU - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/au.svg',
}, {
  ...groupBaseOption,
  'AW - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/aw.svg',
}, {
  ...groupBaseOption,
  'AX - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ax.svg',
}, {
  ...groupBaseOption,
  'AZ - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/az.svg',
}, {
  ...groupBaseOption,
  'BA - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ba.svg',
}, {
  ...groupBaseOption,
  'BB - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/bb.svg',
}, {
  ...groupBaseOption,
  'BD - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/bd.svg',
}, {
  ...groupBaseOption,
  'BE - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/be.svg',
}, {
  ...groupBaseOption,
  'BF - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/bf.svg',
}, {
  ...groupBaseOption,
  'BG - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/bg.svg',
}, {
  ...groupBaseOption,
  'BH - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/bh.svg',
}, {
  ...groupBaseOption,
  'BI - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/bi.svg',
}, {
  ...groupBaseOption,
  'BJ - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/bj.svg',
}, {
  ...groupBaseOption,
  'BL - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/bl.svg',
}, {
  ...groupBaseOption,
  'BM - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/bm.svg',
}, {
  ...groupBaseOption,
  'BN - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/bn.svg',
}, {
  ...groupBaseOption,
  'BO - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/bo.svg',
}, {
  ...groupBaseOption,
  'BQ - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/bq.svg',
}, {
  ...groupBaseOption,
  'BR - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/br.svg',
}, {
  ...groupBaseOption,
  'BS - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/bs.svg',
}, {
  ...groupBaseOption,
  'BT - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/bt.svg',
}, {
  ...groupBaseOption,
  'BV - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/bv.svg',
}, {
  ...groupBaseOption,
  'BW - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/bw.svg',
}, {
  ...groupBaseOption,
  'BY - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/by.svg',
}, {
  ...groupBaseOption,
  'BZ - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/bz.svg',
}, {
  ...groupBaseOption,
  'CA - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ca.svg',
}, {
  ...groupBaseOption,
  'CC - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cc.svg',
}, {
  ...groupBaseOption,
  'CD - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cd.svg',
}, {
  ...groupBaseOption,
  'CF - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cf.svg',
}, {
  ...groupBaseOption,
  'CG - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cg.svg',
}, {
  ...groupBaseOption,
  'CH - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ch.svg',
}, {
  ...groupBaseOption,
  'CI - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ci.svg',
}, {
  ...groupBaseOption,
  'CK - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ck.svg',
}, {
  ...groupBaseOption,
  'CL - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cl.svg',
}, {
  ...groupBaseOption,
  'CM - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cm.svg',
}, {
  ...groupBaseOption,
  'CN - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cn.svg',
}, {
  ...groupBaseOption,
  'CO - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/co.svg',
}, {
  ...groupBaseOption,
  'CP - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cp.svg',
}, {
  ...groupBaseOption,
  'CR - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cr.svg',
}, {
  ...groupBaseOption,
  'CU - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cu.svg',
}, {
  ...groupBaseOption,
  'CV - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cv.svg',
}, {
  ...groupBaseOption,
  'CW - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cw.svg',
}, {
  ...groupBaseOption,
  'CX - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cx.svg',
}, {
  ...groupBaseOption,
  'CY - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cy.svg',
}, {
  ...groupBaseOption,
  'CZ - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cz.svg',
}, {
  ...groupBaseOption,
  'DE - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/de.svg',
}, {
  ...groupBaseOption,
  'DG - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/dg.svg',
}, {
  ...groupBaseOption,
  'DJ - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/dj.svg',
}, {
  ...groupBaseOption,
  'DK - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/dk.svg',
}, {
  ...groupBaseOption,
  'DM - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/dm.svg',
}, {
  ...groupBaseOption,
  'DO - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/do.svg',
}, {
  ...groupBaseOption,
  'DZ - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/dz.svg',
}, {
  ...groupBaseOption,
  'EC - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ec.svg',
}, {
  ...groupBaseOption,
  'EE - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ee.svg',
}, {
  ...groupBaseOption,
  'EG - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/eg.svg',
}, {
  ...groupBaseOption,
  'EH - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/eh.svg',
}, {
  ...groupBaseOption,
  'ER - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/er.svg',
}, {
  ...groupBaseOption,
  'ES - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/es.svg',
}, {
  ...groupBaseOption,
  'ET - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/et.svg',
}, {
  ...groupBaseOption,
  'EU - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/eu.svg',
}, {
  ...groupBaseOption,
  'FI - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/fi.svg',
}, {
  ...groupBaseOption,
  'FJ - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/fj.svg',
}, {
  ...groupBaseOption,
  'FK - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/fk.svg',
}, {
  ...groupBaseOption,
  'FM - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/fm.svg',
}, {
  ...groupBaseOption,
  'FO - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/fo.svg',
}, {
  ...groupBaseOption,
  'FR - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/fr.svg',
}, {
  ...groupBaseOption,
  'GA - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ga.svg',
}, {
  ...groupBaseOption,
  'GB - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gb.svg',
}, {
  ...groupBaseOption,
  'GD - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gd.svg',
}, {
  ...groupBaseOption,
  'GE - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ge.svg',
}, {
  ...groupBaseOption,
  'GF - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gf.svg',
}, {
  ...groupBaseOption,
  'GG - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gg.svg',
}, {
  ...groupBaseOption,
  'GH - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gh.svg',
}, {
  ...groupBaseOption,
  'GI - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gi.svg',
}, {
  ...groupBaseOption,
  'GL - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gl.svg',
}, {
  ...groupBaseOption,
  'GM - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gm.svg',
}, {
  ...groupBaseOption,
  'GN - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gn.svg',
}, {
  ...groupBaseOption,
  'GP - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gp.svg',
}, {
  ...groupBaseOption,
  'GQ - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gq.svg',
}, {
  ...groupBaseOption,
  'GR - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gr.svg',
}, {
  ...groupBaseOption,
  'GS - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gs.svg',
}, {
  ...groupBaseOption,
  'GT - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gt.svg',
}, {
  ...groupBaseOption,
  'GU - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gu.svg',
}, {
  ...groupBaseOption,
  'GW - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gw.svg',
}, {
  ...groupBaseOption,
  'GY - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gy.svg',
}, {
  ...groupBaseOption,
  'HK - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/hk.svg',
}, {
  ...groupBaseOption,
  'HM - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/hm.svg',
}, {
  ...groupBaseOption,
  'HN - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/hn.svg',
}, {
  ...groupBaseOption,
  'HR - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/hr.svg',
}, {
  ...groupBaseOption,
  'HT - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ht.svg',
}, {
  ...groupBaseOption,
  'HU - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/hu.svg',
}, {
  ...groupBaseOption,
  'IC - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ic.svg',
}, {
  ...groupBaseOption,
  'ID - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/id.svg',
}, {
  ...groupBaseOption,
  'IE - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ie.svg',
}, {
  ...groupBaseOption,
  'IL - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/il.svg',
}, {
  ...groupBaseOption,
  'IM - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/im.svg',
}, {
  ...groupBaseOption,
  'IN - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/in.svg',
}, {
  ...groupBaseOption,
  'IO - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/io.svg',
}, {
  ...groupBaseOption,
  'IQ - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/iq.svg',
}, {
  ...groupBaseOption,
  'IR - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ir.svg',
}, {
  ...groupBaseOption,
  'IS - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/is.svg',
}, {
  ...groupBaseOption,
  'IT - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/it.svg',
}, {
  ...groupBaseOption,
  'JE - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/je.svg',
}, {
  ...groupBaseOption,
  'JM - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/jm.svg',
}, {
  ...groupBaseOption,
  'JO - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/jo.svg',
}, {
  ...groupBaseOption,
  'JP - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/jp.svg',
}, {
  ...groupBaseOption,
  'KE - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ke.svg',
}, {
  ...groupBaseOption,
  'KG - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/kg.svg',
}, {
  ...groupBaseOption,
  'KH - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/kh.svg',
}, {
  ...groupBaseOption,
  'KI - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ki.svg',
}, {
  ...groupBaseOption,
  'KM - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/km.svg',
}, {
  ...groupBaseOption,
  'KN - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/kn.svg',
}, {
  ...groupBaseOption,
  'KP - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/kp.svg',
}, {
  ...groupBaseOption,
  'KR - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/kr.svg',
}, {
  ...groupBaseOption,
  'KW - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/kw.svg',
}, {
  ...groupBaseOption,
  'KY - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ky.svg',
}, {
  ...groupBaseOption,
  'KZ - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/kz.svg',
}, {
  ...groupBaseOption,
  'LA - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/la.svg',
}, {
  ...groupBaseOption,
  'LB - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/lb.svg',
}, {
  ...groupBaseOption,
  'LC - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/lc.svg',
}, {
  ...groupBaseOption,
  'LI - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/li.svg',
}, {
  ...groupBaseOption,
  'LK - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/lk.svg',
}, {
  ...groupBaseOption,
  'LR - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/lr.svg',
}, {
  ...groupBaseOption,
  'LS - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ls.svg',
}, {
  ...groupBaseOption,
  'LT - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/lt.svg',
}, {
  ...groupBaseOption,
  'LU - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/lu.svg',
}, {
  ...groupBaseOption,
  'LV - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/lv.svg',
}, {
  ...groupBaseOption,
  'LY - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ly.svg',
}, {
  ...groupBaseOption,
  'MA - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ma.svg',
}, {
  ...groupBaseOption,
  'MC - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/mc.svg',
}, {
  ...groupBaseOption,
  'MD - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/md.svg',
}, {
  ...groupBaseOption,
  'ME - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/me.svg',
}, {
  ...groupBaseOption,
  'MF - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/mf.svg',
}, {
  ...groupBaseOption,
  'MG - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/mg.svg',
}, {
  ...groupBaseOption,
  'MH - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/mh.svg',
}, {
  ...groupBaseOption,
  'MK - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/mk.svg',
}, {
  ...groupBaseOption,
  'ML - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ml.svg',
}, {
  ...groupBaseOption,
  'MM - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/mm.svg',
}, {
  ...groupBaseOption,
  'MN - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/mn.svg',
}, {
  ...groupBaseOption,
  'MO - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/mo.svg',
}, {
  ...groupBaseOption,
  'MP - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/mp.svg',
}, {
  ...groupBaseOption,
  'MQ - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/mq.svg',
}, {
  ...groupBaseOption,
  'MR - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/mr.svg',
}, {
  ...groupBaseOption,
  'MS - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ms.svg',
}, {
  ...groupBaseOption,
  'MT - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/mt.svg',
}, {
  ...groupBaseOption,
  'MU - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/mu.svg',
}, {
  ...groupBaseOption,
  'MV - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/mv.svg',
}, {
  ...groupBaseOption,
  'MW - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/mw.svg',
}, {
  ...groupBaseOption,
  'MX - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/mx.svg',
}, {
  ...groupBaseOption,
  'MY - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/my.svg',
}, {
  ...groupBaseOption,
  'MZ - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/mz.svg',
}, {
  ...groupBaseOption,
  'NA - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/na.svg',
}, {
  ...groupBaseOption,
  'NC - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/nc.svg',
}, {
  ...groupBaseOption,
  'NE - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ne.svg',
}, {
  ...groupBaseOption,
  'NF - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/nf.svg',
}, {
  ...groupBaseOption,
  'NG - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ng.svg',
}, {
  ...groupBaseOption,
  'NI - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ni.svg',
}, {
  ...groupBaseOption,
  'NL - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/nl.svg',
}, {
  ...groupBaseOption,
  'NO - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/no.svg',
}, {
  ...groupBaseOption,
  'NP - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/np.svg',
}, {
  ...groupBaseOption,
  'NR - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/nr.svg',
}, {
  ...groupBaseOption,
  'NU - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/nu.svg',
}, {
  ...groupBaseOption,
  'NZ - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/nz.svg',
}, {
  ...groupBaseOption,
  'OM - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/om.svg',
}, {
  ...groupBaseOption,
  'PA - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/pa.svg',
}, {
  ...groupBaseOption,
  'PC - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/pc.svg',
}, {
  ...groupBaseOption,
  'PE - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/pe.svg',
}, {
  ...groupBaseOption,
  'PF - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/pf.svg',
}, {
  ...groupBaseOption,
  'PG - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/pg.svg',
}, {
  ...groupBaseOption,
  'PH - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ph.svg',
}, {
  ...groupBaseOption,
  'PK - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/pk.svg',
}, {
  ...groupBaseOption,
  'PL - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/pl.svg',
}, {
  ...groupBaseOption,
  'PM - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/pm.svg',
}, {
  ...groupBaseOption,
  'PN - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/pn.svg',
}, {
  ...groupBaseOption,
  'PR - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/pr.svg',
}, {
  ...groupBaseOption,
  'PS - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ps.svg',
}, {
  ...groupBaseOption,
  'PT - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/pt.svg',
}, {
  ...groupBaseOption,
  'PW - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/pw.svg',
}, {
  ...groupBaseOption,
  'PY - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/py.svg',
}, {
  ...groupBaseOption,
  'QA - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/qa.svg',
}, {
  ...groupBaseOption,
  'RE - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/re.svg',
}, {
  ...groupBaseOption,
  'RO - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ro.svg',
}, {
  ...groupBaseOption,
  'RS - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/rs.svg',
}, {
  ...groupBaseOption,
  'RU - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ru.svg',
}, {
  ...groupBaseOption,
  'RW - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/rw.svg',
}, {
  ...groupBaseOption,
  'SA - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sa.svg',
}, {
  ...groupBaseOption,
  'SB - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sb.svg',
}, {
  ...groupBaseOption,
  'SC - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sc.svg',
}, {
  ...groupBaseOption,
  'SD - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sd.svg',
}, {
  ...groupBaseOption,
  'SE - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/se.svg',
}, {
  ...groupBaseOption,
  'SG - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sg.svg',
}, {
  ...groupBaseOption,
  'SH - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sh.svg',
}, {
  ...groupBaseOption,
  'SI - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/si.svg',
}, {
  ...groupBaseOption,
  'SJ - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sj.svg',
}, {
  ...groupBaseOption,
  'SK - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sk.svg',
}, {
  ...groupBaseOption,
  'SL - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sl.svg',
}, {
  ...groupBaseOption,
  'SM - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sm.svg',
}, {
  ...groupBaseOption,
  'SN - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sn.svg',
}, {
  ...groupBaseOption,
  'SO - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/so.svg',
}, {
  ...groupBaseOption,
  'SR - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sr.svg',
}, {
  ...groupBaseOption,
  'SS - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ss.svg',
}, {
  ...groupBaseOption,
  'ST - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/st.svg',
}, {
  ...groupBaseOption,
  'SV - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sv.svg',
}, {
  ...groupBaseOption,
  'SX - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sx.svg',
}, {
  ...groupBaseOption,
  'SY - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sy.svg',
}, {
  ...groupBaseOption,
  'SZ - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sz.svg',
}, {
  ...groupBaseOption,
  'TC - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/tc.svg',
}, {
  ...groupBaseOption,
  'TD - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/td.svg',
}, {
  ...groupBaseOption,
  'TF - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/tf.svg',
}, {
  ...groupBaseOption,
  'TG - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/tg.svg',
}, {
  ...groupBaseOption,
  'TH - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/th.svg',
}, {
  ...groupBaseOption,
  'TJ - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/tj.svg',
}, {
  ...groupBaseOption,
  'TK - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/tk.svg',
}, {
  ...groupBaseOption,
  'TL - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/tl.svg',
}, {
  ...groupBaseOption,
  'TM - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/tm.svg',
}, {
  ...groupBaseOption,
  'TN - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/tn.svg',
}, {
  ...groupBaseOption,
  'TO - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/to.svg',
}, {
  ...groupBaseOption,
  'TR - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/tr.svg',
}, {
  ...groupBaseOption,
  'TT - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/tt.svg',
}, {
  ...groupBaseOption,
  'TV - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/tv.svg',
}, {
  ...groupBaseOption,
  'TW - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/tw.svg',
}, {
  ...groupBaseOption,
  'TZ - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/tz.svg',
}, {
  ...groupBaseOption,
  'UA - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ua.svg',
}, {
  ...groupBaseOption,
  'UG - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ug.svg',
}, {
  ...groupBaseOption,
  'UM - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/um.svg',
}, {
  ...groupBaseOption,
  'UN - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/un.svg',
}, {
  ...groupBaseOption,
  'US - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/us.svg',
}, {
  ...groupBaseOption,
  'UY - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/uy.svg',
}, {
  ...groupBaseOption,
  'UZ - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/uz.svg',
}, {
  ...groupBaseOption,
  'VA - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/va.svg',
}, {
  ...groupBaseOption,
  'VC - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/vc.svg',
}, {
  ...groupBaseOption,
  'VE - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ve.svg',
}, {
  ...groupBaseOption,
  'VG - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/vg.svg',
}, {
  ...groupBaseOption,
  'VI - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/vi.svg',
}, {
  ...groupBaseOption,
  'VN - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/vn.svg',
}, {
  ...groupBaseOption,
  'VU - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/vu.svg',
}, {
  ...groupBaseOption,
  'WF - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/wf.svg',
}, {
  ...groupBaseOption,
  'WS - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ws.svg',
}, {
  ...groupBaseOption,
  'XK - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/xk.svg',
}, {
  ...groupBaseOption,
  'YE - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ye.svg',
}, {
  ...groupBaseOption,
  'YT - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/yt.svg',
}, {
  ...groupBaseOption,
  'ZA - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/za.svg',
}, {
  ...groupBaseOption,
  'ZM - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/zm.svg',
}, {
  ...groupBaseOption,
  'ZW - 自动选择',
  'type': 'url-test',
  'filter': '',
  'include-all': true,
  'icon': 'https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/zw.svg',
}];
